name: Deploy
on:
  push:
    branches: [test]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'none'
      - run: ssh-keyscan -H '34.143.203.251'  >> ~/.ssh/known_hosts
      - run: echo "${{ secrets.ENV }}" > ./.env
      - run: yarn install
      - run: yarn build
      - run: rsync -azP -q --exclude='/ssh/*' . ssh anhchang1412@34.143.203.251:/var/www/beauty-wedding-backend --delete
      - run: ssh anhchang1412@34.143.203.251 "pm2 restart beauty-wedding-backend"